name: startup_app
description: "Car Point App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  yandex_mapkit: ^4.1.0
  geolocator: ^12.0.0
  dio: ^5.5.0+1
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/map_style.json
  uses-material-design: true

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: lib/assets/fonts/HelveticaNeueBlackCondensed.ttf
        - asset: lib/assets/fonts/HelveticaNeueBoldCondensed.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Black.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-BlackItalic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Bold.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-BoldItalic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Heavy.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-HeavyItalic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Italic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Light.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-LightItalic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Medium.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-MediumItalic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Roman.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-Thin.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-ThinItalic.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-UltraLight.ttf
        - asset: lib/assets/fonts/HelveticaNeueCyr-UltraLightItalic.ttf
